version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.0.1
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "CHECK-PRODUCT:1:1,APPLY-PAYMENT:1:1,CHECK-PRODUCT-COMPLETED:1:1,CHECK-PRODUCT-FAILED:1:1,PAYMENT-COMPLETED:1:1,PAYMENT-FAILED:1:1,PRODUCT-ROLLBACK:1:1,ORDER-CREATED:1:1,ORDER-ROLLBACKED:1:1,ORDER-FAILED:1:1,ORDER-COMPLETED:1:1"
      # Topic명:Partition개수:Replica개수
    volumes:
      - ./volume:/var/run/docker.sock
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
