server:
  port: 6010

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/saga_order?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: saga-tester
    password: sagatest
    driver-class-name: com.mysql.cj.jdbc.Driver
    validation-query: SELECT 1

  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

feign:
  client:
    config:
      default:
        connectTimeout: 1
        readTimeout: 4000
