version: '3.7'

services:

  db:
    image: mysql
    container_name: mysql-test
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    security_opt:
      - seccomp=unconfined

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
